INSERT INTO game_list (name) VALUES ('Aventura');
INSERT INTO game_list (name) VALUES ('Corrida');

INSERT INTO games (title, score, year_release, genre, platforms, img_url, short_description, long_description) VALUES ('Forza Horizon 5', 9.4, 2021, 'Racing', 'PC (Microsoft Windows), PlayStation 5, Xbox One, Xbox Series X|S', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3ofx.webp', 'Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open-world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars.', 'Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open-world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars.');
INSERT INTO games (title, score, year_release, genre, platforms, img_url, short_description, long_description) VALUES ('Resident Evil 4', 9.5, 2023, 'Shooter, Puzzle, Adventure', ' Google Stadia, PC (Microsoft Windows), PlayStation 4, Xbox One', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6bo0.webp', 'Resident Evil 4 is a remake of the 2005 original Resident Evil 4 reimagined for 2023 to bring state-of-the-art survival horror. Resident Evil 4 preserves the essence of the original game, while introducing modernized gameplay, a reimagined storyline, and vividly detailed graphics to make this the latest survival horror game where life and death, terror and catharsis intersect.', 'Resident Evil 4 is a remake of the 2005 original Resident Evil 4 reimagined for 2023 to bring state-of-the-art survival horror. Resident Evil 4 preserves the essence of the original game, while introducing modernized gameplay, a reimagined storyline, and vividly detailed graphics to make this the latest survival horror game where life and death, terror and catharsis intersect.');
INSERT INTO games (title, score, year_release, genre, platforms, img_url, short_description, long_description) VALUES ('Far Cry 5', 8.4, 2018, 'Shooter, Adventure', 'PC (Microsoft Windows), PlayStation 5, Xbox One, Xbox Series X|S', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co21a6.webp', 'Welcome to Hope County, Montana, land of the free and the brave, but also home to a fanatical doomsday cult known as The Project at Eden’s Gate that is threatening the community’s freedom. Stand up to the cult’s leader, Joseph Seed and the Heralds, and spark the fires of resistance that will liberate the besieged community. In this expansive world, your limits and creativity will be tested against the biggest and most ruthless baddest enemy Far Cry has ever seen. It’ll be wild and it’ll get weird, but as long as you keep your wits about you, the residents of Hope County can rest assured knowing you’re their beacon of hope.', 'Welcome to Hope County, Montana, land of the free and the brave, but also home to a fanatical doomsday cult known as The Project at Eden’s Gate that is threatening the community’s freedom. Stand up to the cult’s leader, Joseph Seed and the Heralds, and spark the fires of resistance that will liberate the besieged community. In this expansive world, your limits and creativity will be tested against the biggest and most ruthless baddest enemy Far Cry has ever seen. It’ll be wild and it’ll get weird, but as long as you keep your wits about you, the residents of Hope County can rest assured knowing you’re their beacon of hope.');
INSERT INTO games (title, score, year_release, genre, platforms, img_url, short_description, long_description) VALUES ('Grand Theft Auto: San Andreas', 9.3, 2004, 'Shooter, Racing, Adventure', 'Android, iOS, Mac, PC (Microsoft Windows), PlayStation 2, PlayStation 3, PlayStation 4, Xbox, Xbox 360', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2lb9.webp', 'Returning after his mother’s murder to the semi-fictional city of Los Santos (based on Los Angeles), Carl Johnson, a former gang banger, must take back the streets for his family and friends by gaining respect and once again gaining control over the streets. However, a story filled with crime, lies and corruption will lead him to trudge the entire state of San Andreas (based on California and Nevada) to rebuild his life.', 'Returning after his mother’s murder to the semi-fictional city of Los Santos (based on Los Angeles), Carl Johnson, a former gang banger, must take back the streets for his family and friends by gaining respect and once again gaining control over the streets. However, a story filled with crime, lies and corruption will lead him to trudge the entire state of San Andreas (based on California and Nevada) to rebuild his life.');
INSERT INTO games (title, score, year_release, genre, platforms, img_url, short_description, long_description) VALUES ('The Last of Us', 9.2, 2013, 'Shooter, Adventure', 'PlayStation 3', 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7f.webp', 'Twenty years after the outbreak of a parasitic fungus which takes over the neural functions of humans, Joel, a Texan with a tragic familial past, finds himself responsible with smuggling a fourteen year old girl named Ellie to a militia group called the Fireflies, while avoiding strict and deadly authorities, infected fungal hosts and other violent survivors.', 'Twenty years after the outbreak of a parasitic fungus which takes over the neural functions of humans, Joel, a Texan with a tragic familial past, finds himself responsible with smuggling a fourteen year old girl named Ellie to a militia group called the Fireflies, while avoiding strict and deadly authorities, infected fungal hosts and other violent survivors.');


INSERT INTO belonging (list_id, game_id, position) VALUES (1, 2, 0);
INSERT INTO belonging (list_id, game_id, position) VALUES (1, 3, 1);
INSERT INTO belonging (list_id, game_id, position) VALUES (1, 4, 2);
INSERT INTO belonging (list_id, game_id, position) VALUES (1, 5, 3);

INSERT INTO belonging (list_id, game_id, position) VALUES (2, 1, 0);